// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `dev_mock_handle`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MockWireArc`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `discover`, `join_group`, `leave_group`, `next`, `pause`, `play`, `previous`, `refresh_topology`, `set_mute`, `set_volume`, `speaker_state`, `subscribe_speakers`, `subscribe_topology`, `take_event_stream`

/// Deferred warm-up. Blocking ~3–5 s; FRB runs it off the UI isolate.
/// NOT on the #[frb(init)] path. The returned snapshot carries the
/// topology — speaker identities (id / room / model / ip) plus the
/// group identities they belong to, with the coordinator at
/// `members[0]` (D3) — but no live state: volume, mute, and transport
/// are read separately via `speaker_state`. Live state will move to an
/// event-fed cache in v0.4 (ARCHITECTURE.md Open Q7).
Future<Topology> discover() => RustLib.instance.api.crateApiDiscover();

/// Start playback on `group_id` (routed to its coordinator). Blocking SOAP
/// round-trip; FRB surfaces this as a Dart `Future`.
Future<void> play({required String groupId}) =>
    RustLib.instance.api.crateApiPlay(groupId: groupId);

/// Pause playback on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> pause({required String groupId}) =>
    RustLib.instance.api.crateApiPause(groupId: groupId);

/// Skip to the next track on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> next({required String groupId}) =>
    RustLib.instance.api.crateApiNext(groupId: groupId);

/// Skip to the previous track on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> previous({required String groupId}) =>
    RustLib.instance.api.crateApiPrevious(groupId: groupId);

/// Set `speaker_id`'s volume, clamped to `0..=100` by `oto_core::Volume`.
/// The param is **signed** so a negative Dart `int` reaches Rust and
/// clamps to 0 (a `u32` param would throw at FRB's encoder before Rust
/// could clamp). A Dart `int` outside `i32` is rejected at the bridge —
/// unreachable for a volume; the v0.6 UI bounds the slider regardless.
/// Blocking SOAP round-trip; Dart `Future`.
Future<void> setVolume({required String speakerId, required int volume}) =>
    RustLib.instance.api.crateApiSetVolume(
      speakerId: speakerId,
      volume: volume,
    );

/// Set `speaker_id`'s mute state. Blocking SOAP round-trip; Dart `Future`.
Future<void> setMute({required String speakerId, required bool muted}) =>
    RustLib.instance.api.crateApiSetMute(speakerId: speakerId, muted: muted);

/// v0.5.1: fold `speaker_id` into `coordinator_id`'s group. Blocking SOAP
/// round-trip; Dart `Future`. The view refreshes off the debounced
/// topology-event path, NOT a self-trigger here. Unknown id → `NotFound`.
Future<void> joinGroup({
  required String speakerId,
  required String coordinatorId,
}) => RustLib.instance.api.crateApiJoinGroup(
  speakerId: speakerId,
  coordinatorId: coordinatorId,
);

/// v0.5.1: detach `speaker_id` into its own standalone group. Blocking SOAP
/// round-trip; Dart `Future`. The view refreshes off the debounced
/// topology-event path, NOT a self-trigger here. Unknown id → `NotFound`.
Future<void> leaveGroup({required String speakerId}) =>
    RustLib.instance.api.crateApiLeaveGroup(speakerId: speakerId);

/// One-shot read of `speaker_id`'s current volume/mute/transport
/// snapshot. **Not a SOAP round-trip** — reads the event-fed
/// `StateManager` cache in `oto-app` (v0.4 Slice 4); fields are
/// honest-partial (`None` until that property's first event lands).
/// Surfaced as a Dart `Future` like the other commands.
Future<SpeakerStateDto> speakerState({required String speakerId}) =>
    RustLib.instance.api.crateApiSpeakerState(speakerId: speakerId);

/// DEV-ONLY: drive discovery via MockWire (debug builds only). In release
/// builds the body is a no-op that returns `DiscoveryError::Sdk` — the
/// symbol is preserved so FRB-generated bindings still link, but the
/// production wire cannot be replaced from a release-built Dart client.
Future<Topology> devDiscoverMock() =>
    RustLib.instance.api.crateApiDevDiscoverMock();

/// DEV-ONLY: push a `SubscriptionError` event into the held MockWire's
/// channel (debug builds only). Returns an error if `dev_discover_mock`
/// hasn't run yet. In release builds the body is a no-op that returns
/// `CommandError::Sonos`.
Future<void> devPushSubscriptionErrorOnMock({
  required String speakerId,
  required String message,
}) => RustLib.instance.api.crateApiDevPushSubscriptionErrorOnMock(
  speakerId: speakerId,
  message: message,
);

/// DEV-ONLY: push a `TopologyChanged` event into the held MockWire's
/// channel (debug builds only). Mirrors `dev_push_subscription_error_on_mock`
/// — the integration test uses it to drive the v0.5 topology-event path
/// (FRB stream delivery of `ChangeEventDto::TopologyChanged`) without a LAN.
/// Returns an error if `dev_discover_mock` hasn't run yet. In release builds
/// the body is a no-op that returns `CommandError::Sonos`.
Future<void> devPushTopologyChangeOnMock() =>
    RustLib.instance.api.crateApiDevPushTopologyChangeOnMock();

/// Subscribe to the unified v0.4 change-event stream. One call per app
/// instance; the Dart `changeEventsProvider` is the consumer.
/// Stream completes (`onDone` fires) when `discover()` replaces the
/// wire — the Dart provider depends on `discoveryProvider` and
/// auto-rebuilds. Cancel detection via `sink.add(...).is_err()`
/// (FRB pre-check § 3).
Stream<ChangeEventDto> subscribeChangeEvents() =>
    RustLib.instance.api.crateApiSubscribeChangeEvents();

/// The current wire generation — bumped by `discover_with` on every
/// **successful** wire install. The Dart event-stream provider keys its
/// re-subscription on this so a FAILED re-discover (which does not bump it)
/// doesn't tear down the live stream into a one-shot, un-retakeable receiver
/// (review #67-followup #2). `#[frb(sync)]` — a cheap atomic read, called
/// inline from a Riverpod `select`, so it must not be a `Future`.
BigInt currentWireGeneration() =>
    RustLib.instance.api.crateApiCurrentWireGeneration();

@freezed
sealed class ChangeEventDto with _$ChangeEventDto {
  const ChangeEventDto._();

  const factory ChangeEventDto.volume({
    required String speakerId,
    required int volume,
  }) = ChangeEventDto_Volume;
  const factory ChangeEventDto.mute({
    required String speakerId,
    required bool muted,
  }) = ChangeEventDto_Mute;
  const factory ChangeEventDto.playback({
    required String groupId,
    required PlaybackStateDto state,
  }) = ChangeEventDto_Playback;
  const factory ChangeEventDto.track({
    required String groupId,
    required TrackDto track,
  }) = ChangeEventDto_Track;
  const factory ChangeEventDto.subscriptionError({
    required String speakerId,
    required String message,
  }) = ChangeEventDto_SubscriptionError;
  const factory ChangeEventDto.subscriptionRecovered({
    required String speakerId,
  }) = ChangeEventDto_SubscriptionRecovered;

  /// Household topology changed (speakers regrouped). Payload-less: the
  /// Dart `TopologyController` debounces then re-pulls topology on
  /// receipt (v0.5 S1: invalidates `discoveryProvider` → full
  /// re-discover; v0.6 may swap in a lighter SOAP refresh).
  const factory ChangeEventDto.topologyChanged() =
      ChangeEventDto_TopologyChanged;
}

@freezed
sealed class CommandError with _$CommandError implements FrbException {
  const CommandError._();

  const factory CommandError.notFound(String field0) = CommandError_NotFound;
  const factory CommandError.network(String field0) = CommandError_Network;
  const factory CommandError.sonos(String field0) = CommandError_Sonos;
}

class DiscoveredGroup {
  final String id;
  final String coordinator;
  final List<String> members;

  const DiscoveredGroup({
    required this.id,
    required this.coordinator,
    required this.members,
  });

  @override
  int get hashCode => id.hashCode ^ coordinator.hashCode ^ members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          coordinator == other.coordinator &&
          members == other.members;
}

class DiscoveredSpeaker {
  final String id;
  final String roomName;
  final String? model;
  final String ip;

  const DiscoveredSpeaker({
    required this.id,
    required this.roomName,
    this.model,
    required this.ip,
  });

  @override
  int get hashCode =>
      id.hashCode ^ roomName.hashCode ^ model.hashCode ^ ip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredSpeaker &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          roomName == other.roomName &&
          model == other.model &&
          ip == other.ip;
}

@freezed
sealed class DiscoveryError with _$DiscoveryError implements FrbException {
  const DiscoveryError._();

  const factory DiscoveryError.network(String field0) = DiscoveryError_Network;
  const factory DiscoveryError.noDevicesFound() = DiscoveryError_NoDevicesFound;
  const factory DiscoveryError.sdk(String field0) = DiscoveryError_Sdk;
}

enum PlaybackStateDto { stopped, playing, paused, transitioning }

class SpeakerStateDto {
  final int? volume;
  final bool? muted;
  final TransportDto? transport;

  const SpeakerStateDto({this.volume, this.muted, this.transport});

  @override
  int get hashCode => volume.hashCode ^ muted.hashCode ^ transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeakerStateDto &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          muted == other.muted &&
          transport == other.transport;
}

class Topology {
  final List<DiscoveredSpeaker> speakers;
  final List<DiscoveredGroup> groups;

  const Topology({required this.speakers, required this.groups});

  @override
  int get hashCode => speakers.hashCode ^ groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Topology &&
          runtimeType == other.runtimeType &&
          speakers == other.speakers &&
          groups == other.groups;
}

class TrackDto {
  final String? id;
  final String? title;
  final String? artist;
  final String? album;
  final int? trackNumber;
  final BigInt? durationSecs;
  final String? artUri;
  final String? uri;

  const TrackDto({
    this.id,
    this.title,
    this.artist,
    this.album,
    this.trackNumber,
    this.durationSecs,
    this.artUri,
    this.uri,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      trackNumber.hashCode ^
      durationSecs.hashCode ^
      artUri.hashCode ^
      uri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          trackNumber == other.trackNumber &&
          durationSecs == other.durationSecs &&
          artUri == other.artUri &&
          uri == other.uri;
}

class TransportDto {
  final PlaybackStateDto state;
  final BigInt? positionSecs;
  final TrackDto? currentTrack;

  const TransportDto({
    required this.state,
    this.positionSecs,
    this.currentTrack,
  });

  @override
  int get hashCode =>
      state.hashCode ^ positionSecs.hashCode ^ currentTrack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          positionSecs == other.positionSecs &&
          currentTrack == other.currentTrack;
}
