// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `dev_mock_handle`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MockWireArc`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `discover`, `join_group`, `leave_group`, `next`, `pause`, `play`, `previous`, `refresh_topology`, `set_group_mute`, `set_group_volume`, `set_mute`, `set_volume`, `speaker_state`, `subscribe_speakers`, `subscribe_topology`, `take_event_stream`, `track_position`

/// Deferred warm-up. Blocking ~3–5 s; FRB runs it off the UI isolate.
/// NOT on the #[frb(init)] path. The returned snapshot carries the
/// topology - speaker identities (id / room / model / ip) plus the
/// group identities they belong to, with the coordinator at
/// `members[0]` (D3) - but no live state: volume, mute, and transport
/// are read separately via `speaker_state`. Live state moved to an
/// event-fed cache in v0.4.
Future<Topology> discover() => RustLib.instance.api.crateApiDiscover();

/// v0.5.1 fast topology path: a re-discover that SKIPS SSDP.
/// Re-pulls authoritative topology from the current wire (no SSDP, ~tens of ms) and
/// installs a fresh wire seeded from the reachable speaker IPs, through the same
/// wire-replacement lifecycle as `discover()` (gen bump → Dart re-subscribes).
/// Called by the Dart `Discovery.refreshTopology` on a debounced
/// `TopologyChanged`. Glue only - delegates inward, then the `crate::map`
/// representational map, mirroring `discover()` exactly. Blocking SOAP
/// round-trip; FRB surfaces this as a Dart `Future`.
Future<Topology> refreshTopology() =>
    RustLib.instance.api.crateApiRefreshTopology();

/// Start playback on `group_id` (routed to its coordinator). Blocking SOAP
/// round-trip; FRB surfaces this as a Dart `Future`.
Future<void> play({required String groupId}) =>
    RustLib.instance.api.crateApiPlay(groupId: groupId);

/// Pause playback on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> pause({required String groupId}) =>
    RustLib.instance.api.crateApiPause(groupId: groupId);

/// Skip to the next track on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> next({required String groupId}) =>
    RustLib.instance.api.crateApiNext(groupId: groupId);

/// Skip to the previous track on `group_id`. Blocking SOAP round-trip; Dart `Future`.
Future<void> previous({required String groupId}) =>
    RustLib.instance.api.crateApiPrevious(groupId: groupId);

/// Set `speaker_id`'s volume, clamped to `0..=100` by `oto_core::Volume`.
/// The param is **signed** so a negative Dart `int` reaches Rust and
/// clamps to 0 (a `u32` param would throw at FRB's encoder before Rust
/// could clamp). A Dart `int` outside `i32` is rejected at the bridge -
/// unreachable for a volume; the v0.6 UI bounds the slider regardless.
/// Blocking SOAP round-trip; Dart `Future`.
Future<void> setVolume({required String speakerId, required int volume}) =>
    RustLib.instance.api.crateApiSetVolume(
      speakerId: speakerId,
      volume: volume,
    );

/// Set `speaker_id`'s mute state. Blocking SOAP round-trip; Dart `Future`.
Future<void> setMute({required String speakerId, required bool muted}) =>
    RustLib.instance.api.crateApiSetMute(speakerId: speakerId, muted: muted);

/// v0.5.1: set `group_id`'s master volume, clamped to `0..=100` by
/// `oto_core::Volume`. Coordinator-routed (group-scoped). The param is
/// **signed** so a negative Dart `int` clamps to 0 in Rust rather than
/// throwing at the FRB encoder - exactly like `set_volume`; clamping before
/// the SOAP call also avoids the SDK's `.build()` RangeError on > 100.
/// Blocking SOAP round-trip; Dart `Future`. Unknown group → `NotFound`.
Future<void> setGroupVolume({required String groupId, required int volume}) =>
    RustLib.instance.api.crateApiSetGroupVolume(
      groupId: groupId,
      volume: volume,
    );

/// v0.5.1: set `group_id`'s master mute state. Coordinator-routed.
/// Blocking SOAP round-trip; Dart `Future`. Unknown group → `NotFound`.
Future<void> setGroupMute({required String groupId, required bool muted}) =>
    RustLib.instance.api.crateApiSetGroupMute(groupId: groupId, muted: muted);

/// v0.5.1: fold `speaker_id` into `coordinator_id`'s group. Blocking SOAP
/// round-trip; Dart `Future`. The view refreshes off the debounced
/// topology-event path, NOT a self-trigger here. Unknown id → `NotFound`.
Future<void> joinGroup({
  required String speakerId,
  required String coordinatorId,
}) => RustLib.instance.api.crateApiJoinGroup(
  speakerId: speakerId,
  coordinatorId: coordinatorId,
);

/// v0.5.1: detach `speaker_id` into its own standalone group. Blocking SOAP
/// round-trip; Dart `Future`. The view refreshes off the debounced
/// topology-event path, NOT a self-trigger here. Unknown id → `NotFound`.
Future<void> leaveGroup({required String speakerId}) =>
    RustLib.instance.api.crateApiLeaveGroup(speakerId: speakerId);

/// One-shot read of `speaker_id`'s current volume/mute/transport
/// snapshot. **Not a SOAP round-trip** - reads the event-fed
/// `StateManager` cache in `oto-app` (v0.4); fields are
/// honest-partial (`None` until that property's first event lands).
/// Surfaced as a Dart `Future` like the other commands.
Future<SpeakerStateDto> speakerState({required String speakerId}) =>
    RustLib.instance.api.crateApiSpeakerState(speakerId: speakerId);

/// v0.6.1: live SOAP read of `group_id`'s current track position + duration
/// (for the Now Playing progress bar). Blocking SOAP round-trip; Dart `Future`.
/// Reads the coordinator via `Wire::track_position` through the held slot
/// (lock across the SOAP call). Unknown group -> `CommandError::NotFound`.
/// NOT a cache read (unlike `speaker_state`) - position/duration are not
/// evented (neither GENA nor the v0.4 cache carry them).
Future<TrackPositionDto> trackPosition({required String groupId}) =>
    RustLib.instance.api.crateApiTrackPosition(groupId: groupId);

/// DEV-ONLY: drive discovery via MockWire (debug builds only). In release
/// builds the body is a no-op that returns `DiscoveryError::Sdk` - the
/// symbol is preserved so FRB-generated bindings still link, but the
/// production wire cannot be replaced from a release-built Dart client.
Future<Topology> devDiscoverMock() =>
    RustLib.instance.api.crateApiDevDiscoverMock();

/// DEV-ONLY: push a `SubscriptionError` event into the held MockWire's
/// channel (debug builds only). Returns an error if `dev_discover_mock`
/// hasn't run yet. In release builds the body is a no-op that returns
/// `CommandError::Sonos`.
Future<void> devPushSubscriptionErrorOnMock({
  required String speakerId,
  required String message,
}) => RustLib.instance.api.crateApiDevPushSubscriptionErrorOnMock(
  speakerId: speakerId,
  message: message,
);

/// DEV-ONLY: push a `TopologyChanged` event into the held MockWire's
/// channel (debug builds only). Mirrors `dev_push_subscription_error_on_mock` -
/// the integration test uses it to drive the v0.5 topology-event path
/// (FRB stream delivery of `ChangeEventDto::TopologyChanged`) without a LAN.
/// Returns an error if `dev_discover_mock` hasn't run yet. In release builds
/// the body is a no-op that returns `CommandError::Sonos`.
Future<void> devPushTopologyChangeOnMock() =>
    RustLib.instance.api.crateApiDevPushTopologyChangeOnMock();

/// Subscribe to the unified v0.4 change-event stream. One call per app
/// instance; the Dart `changeEventsProvider` is the consumer.
/// Stream completes (`onDone` fires) when `discover()` replaces the
/// wire - the Dart provider depends on `discoveryProvider` and
/// auto-rebuilds. Cancel detection via `sink.add(...).is_err()`
/// (FRB pre-check § 3).
Stream<ChangeEventDto> subscribeChangeEvents() =>
    RustLib.instance.api.crateApiSubscribeChangeEvents();

/// The current wire generation - bumped by `discover_with` on every
/// **successful** wire install. The Dart event-stream provider keys its
/// re-subscription on this so a FAILED re-discover (which does not bump it)
/// doesn't tear down the live stream into a one-shot, un-retakeable receiver
/// (review #67-followup #2). `#[frb(sync)]` - a cheap atomic read, called
/// inline from a Riverpod `select`, so it must not be a `Future`.
///
/// Note: the value returned is the `StateManager` generation. There is no
/// separate wire-side counter - the installed wire is paired with this
/// generation in the slot, so they advance in lockstep; the name reads
/// "wire generation" because that pairing is what callers care about.
BigInt currentWireGeneration() =>
    RustLib.instance.api.crateApiCurrentWireGeneration();

@freezed
sealed class ChangeEventDto with _$ChangeEventDto {
  const ChangeEventDto._();

  const factory ChangeEventDto.volume({
    required String speakerId,
    required int volume,
  }) = ChangeEventDto_Volume;
  const factory ChangeEventDto.mute({
    required String speakerId,
    required bool muted,
  }) = ChangeEventDto_Mute;
  const factory ChangeEventDto.playback({
    required String groupId,
    required PlaybackStateDto state,
  }) = ChangeEventDto_Playback;
  const factory ChangeEventDto.track({
    required String groupId,
    required TrackDto track,
  }) = ChangeEventDto_Track;

  /// v0.5.1 - group master volume changed (per-group, coordinator-routed).
  const factory ChangeEventDto.groupVolume({
    required String groupId,
    required int volume,
  }) = ChangeEventDto_GroupVolume;

  /// v0.5.1 - group master mute changed (per-group, coordinator-routed).
  const factory ChangeEventDto.groupMute({
    required String groupId,
    required bool muted,
  }) = ChangeEventDto_GroupMute;
  const factory ChangeEventDto.subscriptionError({
    required String speakerId,
    required String message,
  }) = ChangeEventDto_SubscriptionError;
  const factory ChangeEventDto.subscriptionRecovered({
    required String speakerId,
  }) = ChangeEventDto_SubscriptionRecovered;

  /// Household topology changed (speakers regrouped). Payload-less: the
  /// Dart `TopologyController` debounces 250 ms then drives a fast
  /// `refreshTopology()` re-pull (a no-SSDP seeded re-discover, ~tens of
  /// ms), with a full SSDP re-discover as the error fallback.
  const factory ChangeEventDto.topologyChanged() =
      ChangeEventDto_TopologyChanged;
}

@freezed
sealed class CommandError with _$CommandError implements FrbException {
  const CommandError._();

  const factory CommandError.notFound(String field0) = CommandError_NotFound;
  const factory CommandError.network(String field0) = CommandError_Network;
  const factory CommandError.sonos(String field0) = CommandError_Sonos;
}

class DiscoveredGroup {
  final String id;
  final String coordinator;
  final List<String> members;

  const DiscoveredGroup({
    required this.id,
    required this.coordinator,
    required this.members,
  });

  @override
  int get hashCode => id.hashCode ^ coordinator.hashCode ^ members.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredGroup &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          coordinator == other.coordinator &&
          members == other.members;
}

class DiscoveredSpeaker {
  final String id;
  final String roomName;
  final String? model;
  final String ip;

  const DiscoveredSpeaker({
    required this.id,
    required this.roomName,
    this.model,
    required this.ip,
  });

  @override
  int get hashCode =>
      id.hashCode ^ roomName.hashCode ^ model.hashCode ^ ip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredSpeaker &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          roomName == other.roomName &&
          model == other.model &&
          ip == other.ip;
}

@freezed
sealed class DiscoveryError with _$DiscoveryError implements FrbException {
  const DiscoveryError._();

  const factory DiscoveryError.network(String field0) = DiscoveryError_Network;
  const factory DiscoveryError.noDevicesFound() = DiscoveryError_NoDevicesFound;
  const factory DiscoveryError.sdk(String field0) = DiscoveryError_Sdk;
}

enum PlaybackStateDto { stopped, playing, paused, transitioning }

class SpeakerStateDto {
  final int? volume;
  final bool? muted;
  final TransportDto? transport;

  const SpeakerStateDto({this.volume, this.muted, this.transport});

  @override
  int get hashCode => volume.hashCode ^ muted.hashCode ^ transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeakerStateDto &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          muted == other.muted &&
          transport == other.transport;
}

class Topology {
  final List<DiscoveredSpeaker> speakers;
  final List<DiscoveredGroup> groups;

  const Topology({required this.speakers, required this.groups});

  @override
  int get hashCode => speakers.hashCode ^ groups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Topology &&
          runtimeType == other.runtimeType &&
          speakers == other.speakers &&
          groups == other.groups;
}

class TrackDto {
  final String? id;
  final String? title;
  final String? artist;
  final String? album;
  final int? trackNumber;
  final BigInt? durationSecs;
  final String? artUri;
  final String? uri;

  const TrackDto({
    this.id,
    this.title,
    this.artist,
    this.album,
    this.trackNumber,
    this.durationSecs,
    this.artUri,
    this.uri,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      trackNumber.hashCode ^
      durationSecs.hashCode ^
      artUri.hashCode ^
      uri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          trackNumber == other.trackNumber &&
          durationSecs == other.durationSecs &&
          artUri == other.artUri &&
          uri == other.uri;
}

/// v0.6.1: point-in-time SOAP read of a group's current track position +
/// duration. Both fields are independently optional: a stream source may
/// report a position with no duration, and a stopped group may report
/// neither. `Duration` narrowed to whole `u64` seconds (lossless - Sonos
/// SOAP time fields carry no sub-second component).
class TrackPositionDto {
  final BigInt? positionSecs;
  final BigInt? durationSecs;

  const TrackPositionDto({this.positionSecs, this.durationSecs});

  @override
  int get hashCode => positionSecs.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackPositionDto &&
          runtimeType == other.runtimeType &&
          positionSecs == other.positionSecs &&
          durationSecs == other.durationSecs;
}

class TransportDto {
  final PlaybackStateDto state;

  /// Always `None` on the production path: the event-fed `StateManager`
  /// cache has no NOTIFY that carries elapsed position, so it only ever
  /// preserves whatever a prior snapshot held (which is nothing). Populated
  /// only by the SOAP-baseline `Wire::speaker_state` used by the
  /// hardware-gated `live_*` tests, and kept so this DTO stays a faithful
  /// mirror of `oto_core::TransportState`. The UI's progress bar reads
  /// `track_position()` / [`TrackPositionDto`] instead.
  final BigInt? positionSecs;
  final TrackDto? currentTrack;

  const TransportDto({
    required this.state,
    this.positionSecs,
    this.currentTrack,
  });

  @override
  int get hashCode =>
      state.hashCode ^ positionSecs.hashCode ^ currentTrack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransportDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          positionSecs == other.positionSecs &&
          currentTrack == other.currentTrack;
}
