// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ChangeEventDto> dco_decode_StreamSink_change_event_dto_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw);

  @protected
  TransportDto dco_decode_box_autoadd_transport_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChangeEventDto dco_decode_change_event_dto(dynamic raw);

  @protected
  CommandError dco_decode_command_error(dynamic raw);

  @protected
  DiscoveredGroup dco_decode_discovered_group(dynamic raw);

  @protected
  DiscoveredSpeaker dco_decode_discovered_speaker(dynamic raw);

  @protected
  DiscoveryError dco_decode_discovery_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DiscoveredGroup> dco_decode_list_discovered_group(dynamic raw);

  @protected
  List<DiscoveredSpeaker> dco_decode_list_discovered_speaker(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  TrackDto? dco_decode_opt_box_autoadd_track_dto(dynamic raw);

  @protected
  TransportDto? dco_decode_opt_box_autoadd_transport_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PlaybackStateDto dco_decode_playback_state_dto(dynamic raw);

  @protected
  SpeakerStateDto dco_decode_speaker_state_dto(dynamic raw);

  @protected
  Topology dco_decode_topology(dynamic raw);

  @protected
  TrackDto dco_decode_track_dto(dynamic raw);

  @protected
  TransportDto dco_decode_transport_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ChangeEventDto> sse_decode_StreamSink_change_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  TransportDto sse_decode_box_autoadd_transport_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChangeEventDto sse_decode_change_event_dto(SseDeserializer deserializer);

  @protected
  CommandError sse_decode_command_error(SseDeserializer deserializer);

  @protected
  DiscoveredGroup sse_decode_discovered_group(SseDeserializer deserializer);

  @protected
  DiscoveredSpeaker sse_decode_discovered_speaker(SseDeserializer deserializer);

  @protected
  DiscoveryError sse_decode_discovery_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DiscoveredGroup> sse_decode_list_discovered_group(
    SseDeserializer deserializer,
  );

  @protected
  List<DiscoveredSpeaker> sse_decode_list_discovered_speaker(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  TrackDto? sse_decode_opt_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  TransportDto? sse_decode_opt_box_autoadd_transport_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PlaybackStateDto sse_decode_playback_state_dto(SseDeserializer deserializer);

  @protected
  SpeakerStateDto sse_decode_speaker_state_dto(SseDeserializer deserializer);

  @protected
  Topology sse_decode_topology(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer);

  @protected
  TransportDto sse_decode_transport_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_change_event_dto_Sse(
    RustStreamSink<ChangeEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_track_dto(
    TrackDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transport_dto(
    TransportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_change_event_dto(
    ChangeEventDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_command_error(CommandError self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_group(
    DiscoveredGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovered_speaker(
    DiscoveredSpeaker self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_error(
    DiscoveryError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_discovered_group(
    List<DiscoveredGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_discovered_speaker(
    List<DiscoveredSpeaker> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_track_dto(
    TrackDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transport_dto(
    TransportDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_playback_state_dto(
    PlaybackStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_speaker_state_dto(
    SpeakerStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_topology(Topology self, SseSerializer serializer);

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer);

  @protected
  void sse_encode_transport_dto(TransportDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
